config/routes.rb
Rails.application.routes.draw do

  root 'feeds#index'

  resources :feeds do
    collection do
      get "latest"
    end
    member do
     resources :feed_entries, only: [:index, :show]

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord

  has_many :feed_entries, dependent: :destroy

  before_save :set_feed_title
  after_save :sync

  validates :url, uniqueness: true, presence: true, :format => URI::regexp(%w(http https))


 # fetch feed from url and update in database
  def sync
    @feed ||= RSS::Feed.fetch(url)
    add_entries(@feed.items)
  end

  private

  def set_feed_title
    @feed = RSS::Feed.fetch(url)
    self.title = @feed.channel.title
  end


  def add_entries(entries)
    entries.each do |entry|
      local_entry = self.feed_entries.where(title: entry.title).first_or_initialize
      local_entry.update_attributes!( url: entry.link, published_at: entry.published_date, guid: entry.guid)
    end
  end
end

app/models/feed_entry.rb
class FeedEntry < ApplicationRecord

  belongs_to :feed

  validates :title, :published_at, :url, presence: true

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:edit, :update, :destroy]


  def index
    @feeds = Feed.all
  end

  def latest
    @entries = FeedEntry.all.order("published_at desc")
  end


  def new
    @feed = Feed.new
  end


  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to feeds_url, notice: 'Feed was successfully created.'
    else
      render :new
    end
  end


  def update
    if @feed.update(feed_params)
      redirect_to feeds_url, notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @feed.destroy
    redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end


    def feed_params
      params.require(:feed).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :feed_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.url %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/latest.html.erb
<div id="recent_articles">
  <h3>Latest Articles</h3>
  <ul>
  <% for entry in @entries %>
    <li>
      <%= link_to h(entry.title), entry.url, target: "_blank" %>

    </li>
  <% end %>
  </ul>
</div>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/layouts/_header.html.erb
<div class="header">
  <ul class="header-nav">
    <li><a href="/">Home</a></li>
    <li><a href="/feeds/latest">Latest</a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RSSFeed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>